# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0003_auto_20170111_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='materias',
            field=models.ManyToManyField(to='pergunte.Materia', verbose_name='Matérias inscritas'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='textoResposta',
            field=models.TextField(verbose_name='Texto da Alternativa'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigoInscricao',
            field=models.CharField(max_length=30, unique=True, verbose_name='Código de inscrição'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='professor',
            field=models.ManyToManyField(to='pergunte.Professor', verbose_name='Professor(a)'),
        ),
    ]
