# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0004_auto_20170113_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='perguntas',
            field=models.ManyToManyField(to='pergunte.Pergunta', verbose_name='Perguntas'),
        ),
    ]
