# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0005_materia_perguntas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='professor',
        ),
        migrations.AddField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pergunte.Professor', verbose_name='Professor(a)'),
            preserve_default=False,
        ),
    ]
