# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0008_auto_20170114_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='turma',
            field=models.CharField(default='A', max_length=1, verbose_name='Turma'),
            preserve_default=False,
        ),
    ]
