# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0010_materia_materiaativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
            },
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'matéria', 'verbose_name_plural': 'matérias'},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'verbose_name': 'pergunta', 'verbose_name_plural': 'perguntas'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'professor', 'verbose_name_plural': 'professores'},
        ),
        migrations.RemoveField(
            model_name='alternativa',
            name='alternativaCorreta',
        ),
        migrations.RemoveField(
            model_name='alternativa',
            name='textoResposta',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='pergunta',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='textoAlternativa',
            field=models.TextField(blank=True, verbose_name='texto da alternativa'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='texto_pergunta',
            field=models.TextField(blank=True, verbose_name='texto da pergunta'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='letra',
            field=models.CharField(max_length=1, verbose_name='alternativa'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(max_length=100, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='materias',
            field=models.ManyToManyField(blank=True, to='pergunte.Materia', verbose_name='matérias inscritas'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='ano',
            field=models.IntegerField(verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigoInscricao',
            field=models.CharField(max_length=30, unique=True, verbose_name='código de inscrição'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='materiaAtiva',
            field=models.BooleanField(default=True, verbose_name='matéria ativa?'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nomeDisciplina',
            field=models.CharField(max_length=200, verbose_name='nome da disciplina'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='perguntas',
            field=models.ManyToManyField(blank=True, to='pergunte.Pergunta', verbose_name='perguntas'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pergunte.Professor', verbose_name='professor(a)'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='semestre',
            field=models.IntegerField(verbose_name='semestre'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='turma',
            field=models.CharField(max_length=1, verbose_name='turma'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativas',
            field=models.ManyToManyField(to='pergunte.Alternativa', verbose_name='alternativas'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='disponivel',
            field=models.BooleanField(verbose_name='pergunta disponível?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(max_length=100, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='universidade',
            field=models.CharField(max_length=100, verbose_name='universidade'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pergunte.Materia', verbose_name='matéria'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='perguntas_respondidas',
            field=models.ManyToManyField(blank=True, to='pergunte.Resposta', verbose_name='perguntas respondidas'),
        ),
    ]
