# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0011_auto_20170120_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='alternativaCorreta',
            field=models.BooleanField(default=False, verbose_name='alternativa correta?'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, verbose_name='titulo/tag'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='alternativas',
            field=models.ManyToManyField(blank=True, to='pergunte.Alternativa', verbose_name='alternativas'),
        ),
    ]
