# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 17:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0012_auto_20170121_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='data_aproximada',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 1, 21, 17, 28, 35, 627043)),
            preserve_default=False,
        ),
    ]
