# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0013_pergunta_data_aproximada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='materia',
        ),
        migrations.AddField(
            model_name='resposta',
            name='respostas',
            field=models.ManyToManyField(to='pergunte.Alternativa', verbose_name='matéria'),
        ),
    ]
