# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0014_auto_20170124_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100, verbose_name='curso')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.RenameField(
            model_name='alternativa',
            old_name='alternativaCorreta',
            new_name='is_correta',
        ),
        migrations.RenameField(
            model_name='alternativa',
            old_name='textoAlternativa',
            new_name='texto_alternativa',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='codigoInscricao',
            new_name='codigo_inscricao',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nomeDisciplina',
        ),
        migrations.AddField(
            model_name='materia',
            name='nome_materia',
            field=models.CharField(default='Matéria em branco', max_length=200, verbose_name='nome da matéria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pergunte.Curso', verbose_name='curso'),
        ),
    ]
