# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0015_auto_20170124_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaRespondida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pergunte.Pergunta', verbose_name='pergunta')),
                ('respostas', models.ManyToManyField(to='pergunte.Alternativa', verbose_name='respostas')),
            ],
            options={
                'verbose_name': 'pergunta respondida',
                'verbose_name_plural': 'perguntas respondidas',
            },
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='respostas',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='perguntas_respondidas',
            field=models.ManyToManyField(blank=True, to='pergunte.PerguntaRespondida', verbose_name='perguntas respondidas'),
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
