# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0017_auto_20170129_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntarespondida',
            name='data_hora_resposta',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 29, 20, 41, 25, 451024), verbose_name='data/hora da resposta'),
            preserve_default=False,
        ),
    ]
