# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0019_pessoa_firebase_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntarespondida',
            name='respostas',
            field=models.ManyToManyField(blank=True, to='pergunte.Alternativa', verbose_name='respostas'),
        ),
    ]
