# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0020_auto_20170211_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='firebase_token',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Token Firebase'),
        ),
    ]
