# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunte', '0021_pessoa_firebase_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL da foto'),
        ),
    ]
